### ISSUE TITLE
Redux 4 compatibility

### ISSUE THREAD

**Issue by farnoy** [AlecAivazis/redux-responsive#102]
Hi, I'm getting an error in `index.d.ts` on v4.3.6 when paired with redux 4.0.0. One such error is `Module '"node_modules/redux/index"' has no exported member 'GenericStoreEnhancer'.`

Can we get updated TS bindings?

**Comment by deadNightTiger** [comment]
I submitted a PR: #103

**Comment by AlecAivazis** [comment]
Thanks for reporting this @farnoy. And thanks for submitting that PR @deadNightTiger  - I merged the PR and about to publish a new version with the updated types. Will wait to close this issue til i have confirmation from you that everything works as expected.

**Comment by AlecAivazis** [comment]
The updated TS bindings should be available in `4.3.7`

**Comment by AlecAivazis** [comment]
@pokonski were you able to get the latest bindings?

**Comment by pokonski** [comment]
We will be updating very soon to this version, so will let you know :)

**Comment by AlecAivazis** [comment]
I'm going to close this to keep things tidy. If there is a problem with the new bindings, please let me know and I will reopen it.
