### ISSUE TITLE
Generic type 'StoreEnhancer' requires 1 type argument(s).

### ISSUE THREAD

**Issue by davidgtu** [AlecAivazis/redux-responsive#107]
I'm trying to start my app and `Generic type 'StoreEnhancer' requires 1 type argument(s).` returns and fails to compile. The error lives in `node_modules/redux-responsive/types/index.d.ts`, so I figure I would start there.

I've tried removing this package and reinstalling it to no avail. I'm not sure what else to do from there.

I would appreciate any help on this. Thank you.

**Comment by AlecAivazis** [comment]
Hey @davidgtu - i'm sorry to hear that you're running into troubles with the type definitions. Unfortunately, I do not use TypeScript, so I am unable to offer much help. I'm going to ping @deadNightTiger who has done most of the work on the type definitions, maybe they can help you out.

**Comment by deadNightTiger** [comment]
@davidgtu are you using redux 3.x? Types were updated to match redux 4.x in 4.3.7, which made them incompatible to the old ones. You can either update redux to 4.x or downgrade redux-responsive to 4.3.6.

**Comment by deadNightTiger** [comment]
@AlecAivazis thinking about it, maybe we should decouple the type declarations from redux altogether. I could just define `Reducer` and `StoreEnhancer` instead of doing imports from redux and it would work as long as it matches what redux expects it to be. I'll make PR over the weekend, probably.

**Comment by davidgtu** [comment]
@deadNightTiger Downgrading redux responsive did the trick. Thank you!

**Comment by AlecAivazis** [comment]
I suppose this change broke the top-level API so it should have been considered a major version. I'm sorry for the trouble this caused @davidgtu. That being said, the change that @deadNightTiger was mentioning sounds great!

**Comment by AlecAivazis** [comment]
@deadnighttiger - I think since we probably don’t want to bump a major version for type definitions I would like to support both 3 and 4. I’m okay not having an explicit test for v3 of redux since I can’t think of a way to have both installed side by side.
