### ISSUE TITLE
Modular build

### ISSUE THREAD

**Issue by ratson** [AlecAivazis/redux-responsive#16]
The current version ships a minified build, which prevent consuming side from taking advantage when doing minification.

It would be nice have a modular build output like [redux](https://github.com/reactjs/redux) does.

**Comment by AlecAivazis** [comment]
Good point, i'll try to put it together sometime this work. Or, if you wanted to submit a PR, I would be happy to review and merge it ASAP

**Comment by AlecAivazis** [comment]
@ratson: I know it's not ideal, but the most recent build has react and redux as external dependencies so the resulting build is signifcantly smaller. I tried to look into the right way to publish a more "modular" (I interpretted as "unbuilt") but couldn't find anything. If you have any suggestions, any advice would be awesome!

**Comment by ratson** [comment]
[Here](https://github.com/reactjs/redux/blob/master/package.json#L24) is how redux doing it, it uses `babel-cli` to build from `src` directory to `lib`.

**Comment by AlecAivazis** [comment]
I just published a version of this that does not minify the output. If you could test it with 

```
npm install redux-responsive@next
```

And let me know if it works or not, that would be great - I'd love to finally close this issue.

**Comment by cbosco** [comment]
Great library!  Thank you for the work.

I wonder if we can re-open this issue? The end goal I think was to create a lib build, e.g.

```
"build:lib": "babel src --out-dir lib",
```

That will let those of us using this library through npm and then browserify/webpack to share common dependencies such as lodash rather than bake them into a monolithic output.

**Comment by AlecAivazis** [comment]
@cbosco thanks for bringing this up, now that webpack supports es2015 modules natively would adding `module: "src/index.js"` allow you to do this? I'm about to push a PR that upgrades the build infrastructure to webpack2 so it's a good opportunity to make sure I am doing whatever I can.

FWIW, my reason to want to avoid running babel directly is that I use webpack to control where the root of my modules is to prevent nasty relative imports and I haven't found a good plugin that allows me to set multiple modules roots.

**Comment by AlecAivazis** [comment]
@ratson @cbosco the new build now provides two non-bundled options. One with babel having run over it (in `/lib`) and one with the raw es6 in `/src`. You should be able to use webpack aliases or equivalent features in other bundlers to use the one appropriate for your use case. Please let me know if there's anything else I can do.
