### ISSUE TITLE
isomorphic apps

### ISSUE THREAD

**Issue by gvas** [AlecAivazis/redux-responsive#17]
On server side redux-responsive populates the responsive state with default values, but on client side it immediately calculates the real values, and puts those into the state. If some component depends on the responsive state then the markup generated on server- and client side will be different, killing the benefits of server side rendering.

I put the throttledHandler() invocation into a setTimeout() in [util/addEventHandler.js](https://github.com/AlecAivazis/redux-responsive/blob/master/src/util/addEventHandlers.js#L25). This solved my problem, but I'm sure there are use cases when this fix isn't acceptable, because the initial rendering on the client must use the correct calculated responsive state.

**Comment by AlecAivazis** [comment]
Server-side rendering is sort of tricky since the browser dimensions aren't sent to the server when the request is made. I'm not really sure what a good solution is but I'm open to suggestions. If you want to make a PR with your changes, I'll check them out and maybe we can figure out the right way forward.

**Comment by gvas** [comment]
I believe we could add a new option to the `createResponsiveStoreEnhancer` factory, named `calculateStateInitially` or something similar. If set to true, it would skip the initial responsive state calculation, and it becomes the responsibility of the library's user to dispatch the `CALCULATE_RESPONSIVE_STATE` action later in the application's lifecycle.

Ok, I'm going to send a PR soon.

**Comment by AlecAivazis** [comment]
Closing this, thanks again!
