### ISSUE TITLE
calculateResponsiveState?

### ISSUE THREAD

**Issue by DarrylD** [AlecAivazis/redux-responsive#24]
`index.js?2645:57Uncaught TypeError: (0 , _reduxResponsive.calculateResponsiveState) is not a function`

Maybe missed in the build?

**Comment by AlecAivazis** [comment]
Thanks for pointing this out @DarrylD. it looks like there is a typo in the project's root `index.js`. I'll fix that now and let you know when it's pushed

**Comment by DarrylD** [comment]
Awesome, I thought i was going crazy, lol.

**Comment by AlecAivazis** [comment]
I just tested locally and published the fix. Feel free to re-open if the problem pops up again.
