### ISSUE TITLE
remove dependency on react-redux

### ISSUE THREAD

**Issue by weshardee** [AlecAivazis/redux-responsive#27]
The documentation says that 

> redux-responsive does not require that you use React as your view library

However, upon importing this into a project I see that it's attempting to require 'react-redux'. I was going to use this with $ngRedux until I discovered this blocker.

**Comment by AlecAivazis** [comment]
Thanks for bringing this up. React is a very recent dependency (it came with the StyleSheet higher-order component). While I work on the right solution, it would probably be good to note that react is not included in the built files so you shouldn't see too many negative side-effects apart from the large download.

**Comment by AlecAivazis** [comment]
Another option, in the meantime is to depend on an older version like `2.0.0`

**Comment by weshardee** [comment]
Thanks for the heads up. I may try explicitly using `2.0.0`. Note that I'm using this with webpack and I'm actually seeing react-redux being built into my project's bundle:

![screen shot 2016-05-17 at 6 05 39 pm](https://cloud.githubusercontent.com/assets/632245/15342319/01cc8012-1c5a-11e6-9f6d-647ba7517815.png)

**Comment by AlecAivazis** [comment]
@weshardee you should be good to go - I removed react and react-redux as explicit dependencies. I'm sure it's going to bite me in the future but I expect that if someone is using react and redux, they won't need me to tell them to download `react-redux` ;)
