### ISSUE TITLE
Please include a LICENSE file

### ISSUE THREAD

**Issue by acidicX** [AlecAivazis/redux-responsive#36]
It would be nice to have a license file just to be sure, as MIT is only stated in the package.json.
Thanks for the great work so far!

**Comment by AlecAivazis** [comment]
Good point - i'll add one now.

**Comment by AlecAivazis** [comment]
@acidicX do you need this to be included in the published package?

**Comment by acidicX** [comment]
@AlecAivazis no, I just needed a clearer definition in the repository. Thanks!
