### ISSUE TITLE
Inject initial state media type

### ISSUE THREAD

**Issue by kandros** [AlecAivazis/redux-responsive#38]
I'm doing server side renderind and getting the device type from user agent on the server (mobile, Tablet, desktop).

Is therea way to inject the initial media type beside   passing a browser object as redux initial state?

**Comment by dan-lee** [comment]
Yeah, I also need this. I think we'd need something like an initial breakpoint which does not care about browser size yet.

**Comment by AlecAivazis** [comment]
Currently, there isn't but I'll try to get something together this week. In the meantime, you can disable the responsive state calculation on the server by setting `calculateStateInitially: false` to the store enchaner as described in the docs and then triggering it on the client - at least that way the client can cleanly bootstrap from the server.

**Comment by dan-lee** [comment]
Cool thank you!
I already did that, according to the docs :)

**Comment by ryan-sherpa** [comment]
Any update here?

**Comment by AlecAivazis** [comment]
I just submmited a PR that should provide this functionality - anyone care to take it for a spin?

**Comment by AlecAivazis** [comment]
You can now set the initial media type by pass it as the `initialMediaType` argument to the reducer factory
