### ISSUE TITLE
Expose event listener for window 

### ISSUE THREAD

**Issue by dan-lee** [AlecAivazis/redux-responsive#40]
I am using server side rendering like stated in the docs.

Now I see that the event listener responsible for the state changes is added in `./src/util/addEventHandlers.js` but only when `window` is available. Of course this doesn't work on SSR.
What I needed to do is to add my own event listener in my application, like so:
```js
window.addEventListener('resize', throttle(
  () => Store.dispatch(calculateResponsiveState(window)),
  50
))
```

Would it be possible to expose this listener from your library?

For example I could use it like: 
```js
window.addEventListener('resize', responsiveStateResizeListener)
// or
addResponsiveStateResizeListener(window)
```

Thanks 

PS. Cool library🎈

**Comment by AlecAivazis** [comment]
@dan-lee - thanks for the kind remarks 😄 

Do you mind providing a bit more detail about the particular thing you're trying to accomplish? I'm a bit confused about your usage of window on the server.

**Comment by dan-lee** [comment]
Sorry for the confusion. The event listener is implemented on the client side part (the entry point for the browser). I need to do this or otherwise I don't see any state changes triggered when the browser is resized.

**Comment by AlecAivazis** [comment]
So the event listener is added by the store enhancer here: https://github.com/AlecAivazis/redux-responsive/blob/002b0b222021a9fba685f478c289dac4289d8ca6/src/util/addEventHandlers.js#L32

When you create the store in the client entry point, it will grab the window and things should "just work" - are you seeing something different?

**Comment by dan-lee** [comment]
Okay you're right, I just checked it inside a fresh boilerplate project and it works in there.

Also I checked `getEventListeners(window).resize` in my main project and I see one listener registered by `redux-responsive`. But somehow no action is dispatched on resize. I don't get why, to be honest 😕

**Comment by AlecAivazis** [comment]
Hmmm that's weird - do you think you could throw together a little example that shows the behavior so I can help you debug it?

**Comment by AlecAivazis** [comment]
@dan-lee: i'm going to close this to keep things tidy. If you are able to throw together an example, please open up another issue so we can figure out what's going on.

**Comment by dan-lee** [comment]
@AlecAivazis Sure! I'll see if I can create a reproducible project, when I've got time. But for now it's of lower priority, because it works fine with the workaround.
