### ISSUE TITLE
redux-responsive stops working when redux devtools are used

### ISSUE THREAD

**Issue by jharris4** [AlecAivazis/redux-responsive#42]
I just added https://github.com/zalmoxisus/redux-devtools-extension to my redux store, and it caused redux-responsive to stop responding to window resize events / dispatching actions. The only change I made was to add window.devToolsExtension like so:

```
const finalCreateStore = compose(
    applyMiddleware(...middlewares),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )(createStore);

const rootReducer = combineReducers({
    responsive: responsiveReducer,
    ...reducers
  });

const store = finalCreateStore(rootReducer, initialState, createResponsiveStoreEnhancer());
```

If I remove the window.devToolsExtension, things start working properly again.

**Comment by jharris4** [comment]
The advice in the readme helped me figure out how to fix the issue. I changed the code to the following and it's working again now:

```
const finalCreateStore = compose(
    createResponsiveStoreEnhancer(),
    applyMiddleware(...middlewares),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )(createStore);
```

**Comment by AlecAivazis** [comment]
Awesome, glad to hear that the docs helped you out! Please let me know if you run into any more issues :)
