### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by srfoster** [AlecAivazis/redux-responsive#43]
I'm probably doing something noobish, but I can't get redux-responsive to work in my project.

I did this:

    npm install --local --save https://github.com/AlecAivazis/redux-responsive/archive/3.0.0.tar.gz

I have a redux-responsive folder in the node_modules directory.  But I get "Error: Cannot resolve module 'redux-responsive' " when I try to import from "redux-responsive".

I'm sort of new to node in general, so my error might not have anything to do with your package in particular.  But would you mind letting me know what the intended installation process is supposed to be?

**Comment by srfoster** [comment]
I should add that the same happened when I did the more standard:

    npm install redux-responsive

**Comment by AlecAivazis** [comment]
Hmm that's strange. What you described is the normal process. It sounds like whatever you are using to build your projects can't find the node_modules dir. Are you using webpack?

**Comment by srfoster** [comment]
Yes.  In fact, I am using this stack here:

https://github.com/rangle/typescript-react-redux-starter

Honestly, I don't know enough about node's module loading to really know where to look for the breakdown.  I do know that other modules in node_modules seem to be loading correctly, though.

**Comment by AlecAivazis** [comment]
Hmmm I'm not sure your problem is related with this package but let's make sure: if you go into your `node_modules` directory, do you see a `redux-responsive` folder with `index.js` and `react.js`?

**Comment by srfoster** [comment]
I do.  I'll file an issue on that other project and see if they have insights.

**Comment by AlecAivazis** [comment]
hmm okay - ill close this isuue but feel free to reopen if you still have problems
