### ISSUE TITLE
Issue with `Symbol` in redux-responsive 3.1.0

### ISSUE THREAD

**Issue by crast** [AlecAivazis/redux-responsive#47]
I upgraded to redux-responsive 3.1.0 and I am having issues in IE 11 with missing the property `Symbol` - Turns out it's being referenced in a big blob of already-minified code distributed with redux-responsive. 

I tried adding a polyfill for `Symbol` to the root of my app, even forcing the polyfill on the `window` object with no luck. Probably won't help if I give you the trace in IE, because it's all in the middle of a minified mess (I'm currently running a development build so the rest of my source is readable other than redux-responsive), but I can if desired.

Downgrading to redux-responsive 3.0.0 fixes the issue.

I did check with `git diff v3.0.0..master` and there's no notable changes to dependencies.json or to the code which would include references to / dependency on ES6 `Symbol` type, and yet, there it is. It's possible this is related to #16 but in either case, it seems like something got changed between releases and something got added in from an upgrade in your local environment.

Is there any way to release redux-responsive in a non-minified form with dependencies not 'baked in', like most other node libraries? This way we can use the polyfills of our own choice and the toolchain we already might have.

**Comment by AlecAivazis** [comment]
Darn! Sorry you ran into this @crast, i'll try to get a fix for this very soon.

**Comment by AlecAivazis** [comment]
So I published a non-minified version of this package under the `next` tag and think I have removed the dependency on Symbol. It can be installed with:
```
npm i --save redux-responsive@next
```

If you could run this with your code and tell me if it works or not, I would really appreciate it.

**Comment by phoenix2x** [comment]
I've run into the same issue with 3.1.0, redux-responsive@next works fine.

Thanks.

**Comment by AlecAivazis** [comment]
Thanks for letting me know @phoenix2x - i'll go ahead and publish the new version. Please let me know if you guys still run into issues

**Comment by AlecAivazis** [comment]
Im going to close this since I think it's handled. Please open up another ticket if that's not the case
