### ISSUE TITLE
browser.height sometimes returns undefined

### ISSUE THREAD

**Issue by Ragnaroek** [AlecAivazis/redux-responsive#50]
Maybe the others properties too, but we use only this property where the problem occured.

It returns undefined in a non-deterministic way. Probably because window.innerHeight returns this value? Maybe something can be done?

Browser Firefox 49.0.1

**Comment by AlecAivazis** [comment]
Hm, without a reliable way to reproduce, it's hard to figure out what's causing the problem. It seems `window.innerHeight` is no not support in IE8 and below, could that be the issue?

**Comment by AlecAivazis** [comment]
@Ragnaroek the `height` attribute will be removed in `v4` so i'm going to close this - if you need to add it to your responsive state, there will be directions in the readme for how to migrate forward
