### ISSUE TITLE
Browser width is changing with pinch to zoom

### ISSUE THREAD

**Issue by pistol-pete** [AlecAivazis/redux-responsive#55]
Hi, when enabling pinch to zoom using `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.5, user-scalable=yes">`

the browser width value that is presented is changing when pinch to zoom is used on mobile devices (tested on android chrome, iOS chrome and safari). Is this intended?
I had a play with the built node module code to see if I could fix it. I ended up overriding the innerWidth in index.js line 4755 to `var innerWidth = document.documentElement.clientWidth;`

**Comment by pistol-pete** [comment]
FYI I have forked the code (https://github.com/pistol-pete/redux-responsive) and applied my fix to the source now and pushed as a new npm package "redux-responsive-pistol-pete".

**Comment by AlecAivazis** [comment]
Awesome! Nice to see the fix is working. Why not just make a PR and we can encorporate your changes into this project?

**Comment by AlecAivazis** [comment]
@pistol-pete the width attribute will be removed in `v4` so I'm going to close this - if you see this affecting the responsive state objects, please open another ticket
