### ISSUE TITLE
Suddenly getting an error without making any changes - Error: Could not find responsive state reducer  Performance mode can only be used if the responsive reducer is at the root of your reducer tree

### ISSUE THREAD

**Issue by Slapbox** [AlecAivazis/redux-responsive#70]
`Uncaught (in promise) Error: Could not find responsive state reducer - Performance mode can only be used if the responsive reducer is at the root of your reducer tree.If you are still running into trouble, please open a ticket on github.`

I haven't made any code changes and I have tried reinstalling all NPM packages, clearing my stored state files, rebooting the machine, etc. I have no idea where this popped up from. Any idea?

**Comment by Slapbox** [comment]
It has been working fine for several months, and then, poof. I rolled back to old commits in my git repo as well, but the same error..

**Comment by Slapbox** [comment]
`const actionCreators = {
  ...noteActions,
  push,
};

const logger = createLogger({
  level: 'info',
  collapsed: true,
});

const router = routerMiddleware(hashHistory);

const enhancer = compose(
  responsiveStoreEnhancer,
  applyMiddleware(thunk, router, logger),
  storage(),
  onExitStorage(),
  window.devToolsExtension ? window.devToolsExtension({ actionCreators }) : nope => nope
);


export default function configureStore(initialState: Object | void) {
  const store = createStore(rootReducer, initialState, enhancer);

  if (window.devToolsExtension) {
    window.devToolsExtension.updateStore(store);
  }

  if (module.hot) {
    module.hot.accept('../reducers', () => {
      const nextRootReducer = require('../reducers');
      store.replaceReducer(nextRootReducer);
    });
  }
  return store;
}
`

If I remove `onExitStorage()` it works fine, but `onExitStorage()` is almost identical to `storage()` and I can't understand why this would interfere with `redux-responsive`.

Thanks for any thoughts you might have.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @slapbox. I'm not sure why this is happening all Of the sudden. I saw you had mentioned that it was failing because of a redux store enhancer you were using - can u post the contents here?

**Comment by Slapbox** [comment]
Thanks for responding @AlecAivazis 

I removed that comment because it turned out I was mistaken. In the end I moved redux-responsive to the root reducer and that seems to have fixed it. I just can't understand how that would arise seemingly out of thin air, but such is programming sometimes. Thanks again for your response!

**Comment by AlecAivazis** [comment]
Ah cool, well i'm glad you sorted it out. Please let me know if you run into any issues. This need for the reducer to be at the root is a really annoying side effect of the way I implemented things and I would love to not require it. Hopefully that will happen soon 😄
