### ISSUE TITLE
Allow config option to recalculate on every resize event

### ISSUE THREAD

**Issue by L-u-k-e** [AlecAivazis/redux-responsive#71]
Currently, unless I am mistaken, if you want to recalculate the responsive state every time the browser is resized (as opposed to only recalculating when a new breakpoint matches), you have to add an event listener to the window  #object and emit an action manually. The docs give this example:

```
// store.js

import {calculateResponsiveState} from 'redux-responsive'

const store = ...

window.addEventListener('resize', () => store.dispatch(calculateResponsiveState(window)))
```

Can this functionality be made easier by the library? It seems like it shouldn't be to hard to allow for a configuration option to be specified when creating the store enhancer. e.g. `createResponsiveStoreEnhancer({ alwaysRecalculate: true })`

**Comment by AlecAivazis** [comment]
Hey @L-u-k-e, thanks for the feedback. When this library was first written, what you're suggesting was the default behavior. It wasn't until [version 4](https://github.com/AlecAivazis/redux-responsive/wiki/Changelog) that the `alwaysRecalculate` behavior was removed. What i found after collecting way more feedback than i thought possible was that the number of times where you actually want the browser to recalculate on every resize is much smaller than when you only want the library to change at the "right" time (when the state actually transitions between them). For those users who needed fine grain updates (for example, if you add `browser.width` to the state), you can always add the little bit of code you suggested. 

For more details/motivation, you can see the discussion here: https://github.com/AlecAivazis/redux-responsive/pull/59

**Comment by L-u-k-e** [comment]
Okay, thanks for responding, I'll close this issue since you don't plan on implementing this. 

I ended up making this behavior a middleware actually:

```
import { calculateResponsiveState } from 'redux-responsive';

export default function resizeListenerMiddleware() {
  return next => {
    if (window) {
      window.addEventListener('resize', () => next(calculateResponsiveState(window)));
    }
    return (action) => {
      next(action);
    }
  };
}
```
