### ISSUE TITLE
greaterThanOrEqual returns undefined

### ISSUE THREAD

**Issue by jawinn** [AlecAivazis/redux-responsive#72]
When I use the example for greaterThanOrEqual, I cannot seem to see a way to use it, or it is not returning the right value.

`browser.greaterThanOrEqual.small` always returns undefined.
`browser.greaterThan.small` works correctly.

greaterThanOrEqual _does_ exist within the browser object. I tried also using greaterThanOrEqual as a function, thinking it worked differently than the built in methods, but that returns 'not a function'.

My reducer:
```
    browser: createResponsiveStateReducer(
      {
        // greaterThanOrEqual doesn't seem to be working. so just use greaterThan with 1 pixel less.
        extraSmall: 500,
        small: 768,
        medium:1024,
        large: 1270,
        extraLarge: 1920
      },
      {
        extraFields: ({greaterThan, is}) => ({
          // greaterThanOrEqual is built by transforming greaterThan
          greaterThanOrEqual: transform((result, value, mediaType) => {
            // and combining the value with the `is` field
            result[mediaType] = value || is[mediaType];
          }, greaterThan)
        })
      }
    ),
```

Side note, it might be a good idea just to make this function a part of redux-responsive, considering its common usage.

**Comment by AlecAivazis** [comment]
Hey @jawinn sorry it took me so long to reply, and thanks for reporting this error in the documentation. I'll submit a PR with a fix but in the meantime, `greaterThanOrEqual` should look like:
```javascript
                    // greaterThanOrEqual is built by transforming greaterThan
                    greaterThanOrEqual: transform(greaterThan, (result, value, mediaType) => {
                        // and combining the value with the `is` field
                        result[mediaType] = value || is[mediaType]
                    }, {})
```
