### ISSUE TITLE
Build size is too large

### ISSUE THREAD

**Issue by bradbirnbaum** [AlecAivazis/redux-responsive#76]
The index.js file looks to contain a lot of the lodash functions.  As most projects already use lodash this is causing bloat in the package.

**Comment by AlecAivazis** [comment]
thanks for reporting this @bradbirnbaum and sorry for the recent increase in bundle size. I upgraded to webpack2 and am not surprised to hear that something wasn't right - the old setup took a bit to fine tune for optimal consumption. I'm going to try to just remove the lodash dependency all together sometime tonight as it is mostly just there to save a few lines of code, but doesn't seem worth the extra dependency anymore.

**Comment by bradbirnbaum** [comment]
Great, thanks

**Comment by AlecAivazis** [comment]
So #77 reduces the bundle size from 150kb (which was a bit obscene, to be honest) to 25.8kb which still feels big but makes me a lot more comfortable. @bradbirnbaum hope this is a satisfactory reduction!
