### ISSUE TITLE
Unsure of how to setup correctly with SSR

### ISSUE THREAD

**Issue by grimunit** [AlecAivazis/redux-responsive#81]
I was super excited when I saw that someone had already created something to solve my problem of dealing with window events in react and exposing them to redux on page load. I was able to get it working out of the box just fine. 

However as soon as I added the `extraFields` function, I'm now unable to get it to match the SSR'ed store and I want to make sure I'm doing it correctly.

Basically I want to do exactly what you showed in your example, have the `window.innerWidth` available and calculated on page load. Also I'm having it update on each resize.

Here's how I have it set up on my client side:

```
// clientStoreSetup.js
const store = configureStore({
  initialState,
  platformDeps: { uuid },
  platformReducers: {
    found: found.reducer,
    browser: createResponsiveStateReducer(null, {
      extraFields: () => ({
        width: window.innerWidth,
      }),
    }),
  },
  platformMiddleware: [reportingMiddleware],
  platformStoreEnhancers: [
    ...found.storeEnhancers,
    createResponsiveStoreEnhancer(null, {   // I also tried without passing the extraFields to enhancer
      extraFields: () => ({
        width: window.innerWidth,
      }),
    }),
  ],
});

// Need to immediately dispatch responsive state recalculation
store.dispatch(calculateResponsiveState(window));
```

And on the server:

```
// serverStoreSetup.js
const createStore = (found, req): Object =>
  configureStore({
    initialState: {
      ...initialState,
      device: {
        ...initialState.device,
        host: getHost(req),
      },
      intl: {
        ...initialState.intl,
        currentLocale: getLocale(req),
        initialNow: Date.now(),
      },
    },
    platformReducers: { found: found.reducer },
    platformStoreEnhancers: [
      ...found.storeEnhancers,
      createResponsiveStoreEnhancer({ calculateInitialState: false }),
    ],
  });
```

I'm not sure if the `createResponsiveStateReducer` and `createResponsiveStoreEnhancer` are supposed to match or are supposed to be different. I tried both, but neither seem to work.

I basically get the error: 

```
TypeError: Cannot read property 'width' of undefined
```

**Comment by grimunit** [comment]
Actually I think the root of the problem isn't the addition of the `extraFields` property. It's the fact that none of the properties on the new `browser` reducer are defined initially and so any reference to one of that reducers properties is undefined upon initial render of any component and breaks with an `undefined` error.

**Comment by AlecAivazis** [comment]
Hey @grimunit! Sorry, i haven't gotten a chance to go through this very deeply yet, I'll try to spend some time this weekend and figure out what exactly is wrong if you don't get to it before then. I haven't tested setting an initial state with extra fields. Sorry for any inconvenience this has caused.

**Comment by grimunit** [comment]
Hey no problem Alec, I think I actually found the cause of it. It looks like I need to have the `responsiveStateReducer` also specified in my server-side store setup. So if you take what I had above:

```
// serverStoreSetup.js
const createStore = (found, req): Object =>
  configureStore({
    initialState: {
      ...initialState,
      device: {
        ...initialState.device,
        host: getHost(req),
      },
      intl: {
        ...initialState.intl,
        currentLocale: getLocale(req),
        initialNow: Date.now(),
      },
    },
    platformReducers: { found: found.reducer },
    platformStoreEnhancers: [
      ...found.storeEnhancers,
      createResponsiveStoreEnhancer({ calculateInitialState: false }),
    ],
  });
```

I had to also add the `responsiveStateReducer` like so:

```
const createStore = (found, req): Object =>
  configureStore({
    initialState: {
      ...initialState,
      device: {
        ...initialState.device,
        host: getHost(req),
      },
      intl: {
        ...initialState.intl,
        currentLocale: getLocale(req),
        initialNow: Date.now(),
      },
    },
    platformReducers: {
      found: found.reducer,
      browser: responsiveStateReducer,
    },
    platformStoreEnhancers: [
      ...found.storeEnhancers,
      createResponsiveStoreEnhancer({ calculateInitialState: false }),
    ],
  });
```

I don't think that's mentioned in the docs that you have to do that. It mentions setting the initial media type on the server if you already know what it's going to be from the useragent, but doesn't explicitly say you need to define the reducer on the server side first. It makes sense that you would need to do that so that your initial reducers match up, but should that be added to the README? Or am I incorrect in assuming that it needs to be setup that way, and mine just happens to work with it there?

**Comment by grimunit** [comment]
Well I got it working so I'll close it, but let me know if you'd want me to do a PR to add that clarification in the documentation if my assumption is correct. Also I'm loving this library, so thanks 😄

**Comment by AlecAivazis** [comment]
Ah cool! Well i'm glad you figured it out. You're definitely right that the documentation could be more clear with a reminder to include the reducer on the server, but I don't think we need to include a code block showing a specific example. If you want to submit a PR with that change, i would really appreciate it!

Thanks for the kind words :) Glad you're enjoying it. Please let me know if you run into any more bugs.
