### ISSUE TITLE
index.d.ts is not published to npm

### ISSUE THREAD

**Issue by deadNightTiger** [AlecAivazis/redux-responsive#88]
In version 4.3.2 there is no `index.d.ts` in the npm package.

**Comment by AlecAivazis** [comment]
Thanks for pointing this out @deadNightTiger - this should be fixed on v4.3.3. I'll keep this ticket open until you confirm|

**Comment by AlecAivazis** [comment]
Just pulled this into one of my projects and verified the typing file is present. Thanks again for reporting this @deadNightTiger
