### ISSUE TITLE
Typescript typings are problematic

### ISSUE THREAD

**Issue by icopp** [AlecAivazis/redux-responsive#92]
The default `IBreakPoints`, etc limit uses to *only* those keys, requiring casting any other combination of keys with `as any` to trick the typing.

**Comment by AlecAivazis** [comment]
Thanks again for another report @icopp - I personally do not use typescript so I have been relying on the contributions from others to keep the type definitions correct. 

If you have a suggestion to fix the type definitions to allow for breakpoints of any name, I'd definitely make sure it gets through although I'll probably have to rope someone in to review the actual type definition.

**Comment by AlecAivazis** [comment]
Closing this since it was addressed in #94
