### ISSUE TITLE
Breaks when run in Jest tests: "middleware is not a function"

### ISSUE THREAD

**Issue by icopp** [AlecAivazis/redux-responsive#93]
```
    TypeError: middleware is not a function

      at node_modules/redux/lib/applyMiddleware.js:49:16
          at Array.map (<anonymous>)
      at node_modules/redux/lib/applyMiddleware.js:48:27
      at node_modules/redux-responsive/index.js:141:37
      at createStore (node_modules/redux/lib/createStore.js:64:33)
```

This doesn't happen when actually running the app normally, just during tests, which makes me suspect it's something `window`-related or similar.

This is with `redux-responsive` 4.3.4 and `redux` 3.7.2.

**Comment by icopp** [comment]
Also, some poking at the internals of the `redux-response/index.js` file tell me that the arguments getting passed into `createStore` are `{ '0': [Function], '1': undefined, '2': undefined }`.

**Comment by AlecAivazis** [comment]
Hey @icopp thank you for reporting this. Unfortunately, I am unable to reproduce this error - executing `yarn test` runs without any hitches. It also passes on travis ([here](https://travis-ci.org/AlecAivazis/redux-responsive) a link to the build that shows all the tests passing. 

How are you executing the tests?

**Comment by icopp** [comment]
I've got a frankenstein configuration that's using [react-app-rewired](https://github.com/timarney/react-app-rewired) to run tests via `react-scripts` 1.0.13, but with [ts-jest](https://github.com/kulshekhar/ts-jest) injected into the config. `ts-jest` theoretically shouldn't be affecting anything here (it's not transforming any plain `js` files), but something in the `react-scripts` repo might be monkeying with things.

**Comment by icopp** [comment]
I think this ultimately lies elsewhere in the stack, since after a bunch of rejiggering I've managed to get the same error (tracking to the same line in Redux) apparently coming from other middleware packages. Sorry for the bother!
